stages:
  - build
  - test

image: registry.app.unistra.fr/montavont/img-docker/progsys:latest

build_6.3:
  stage: build
  script:
    - cd 06-signaux/03-trier
    - scons
  artifacts:
    paths:
      - 06-signaux/03-trier/trier

# run tests using the binary build before
test_6.3:
  stage: test
  needs: [build_6.3]
  script:
  - |
    echo "starting test"
    cd 06-signaux/03-trier
    bash tests.sh
