stages:
  - build
  - test

image: registry.app.unistra.fr/montavont/img-docker/progsys:latest

build_4.3:
  stage: build
  script:
    - cd 04-exec/03-myexeclp
    - scons
  artifacts:
    paths:
      - 04-exec/03-myexeclp/myexeclp

# run tests using the binary build before
test_4.3:
  stage: test
  needs: [build_4.3]
  script:
  - |
    echo "starting test"
    cd 04-exec/03-myexeclp
    bash tests.sh
