stages:
  - build
  - test

image: registry.app.unistra.fr/montavont/img-docker/progsys:latest

build_6.2:
  stage: build
  script:
    - cd 06-signaux/02-masquer
    - scons
  artifacts:
    paths:
      - 06-signaux/02-masquer/masquer

# run tests using the binary build before
test_6.2:
  stage: test
  needs: [build_6.2]
  script:
  - |
    echo "starting test"
    cd 06-signaux/02-masquer
    bash tests.sh
