stages:
  - build
  - test

image: registry.app.unistra.fr/montavont/img-docker/progsys:latest

build_4.1:
  stage: build
  script:
    - cd 04-exec/01-execution-cmd
    - scons
  artifacts:
    paths:
      - 04-exec/01-execution-cmd/execmd

# run tests using the binary build before
test_4.1:
  stage: test
  needs: [build_4.1]
  script:
  - |
    echo "starting test"
    cd 04-exec/01-execution-cmd
    bash tests.sh
