stages:
  - build
  - test

image: registry.app.unistra.fr/montavont/img-docker/progsys:latest

build_5.1:
  stage: build
  script:
    - cd 05-redirections/01-presence
    - scons
  artifacts:
    paths:
      - 05-redirections/01-presence/presence

# run tests using the binary build before
test_5.1:
  stage: test
  needs: [build_5.1]
  script:
  - |
    echo "starting test"
    cd 05-redirections/01-presence
    bash tests.sh
