stages:
  - build
  - test

image: registry.app.unistra.fr/montavont/img-docker/progsys:latest

build_3.2:
  stage: build
  script:
    - cd 03-processus/02-multiple-fils
    - scons
  artifacts:
    paths:
      - 03-processus/02-multiple-fils/nfils

# run tests using the binary build before
test_3.2:
  stage: test
  needs: [build_3.2]
  script:
  - |
    echo "starting test"
    cd 03-processus/02-multiple-fils
    bash tests.sh
