stages:
  - build
  - test

image: registry.app.unistra.fr/montavont/img-docker/progsys:latest

build_2.4:
  stage: build
  script:
    - cd 02-repertoires/04-copie-arbo
    - scons
  artifacts:
    paths:
      - 02-repertoires/04-copie-arbo/copie-arbo

# run tests using the binary build before
test_2.4:
  stage: test
  needs: [build_2.4]
  script:
  - |
    echo "starting test"
    cd 02-repertoires/04-copie-arbo
    bash tests.sh
