stages:
  - build
  - test

image: registry.app.unistra.fr/montavont/img-docker/progsys:latest

build_2.2:
  stage: build
  script:
    - cd 02-repertoires/02-affichage
    - scons
  artifacts:
    paths:
      - 02-repertoires/02-affichage/monls

# run tests using the binary build before
test_2.2:
  stage: test
  needs: [build_2.2]
  script:
  - |
    echo "starting test"
    cd 02-repertoires/02-affichage
    bash tests.sh
