stages:
  - build
  - test

image: registry.app.unistra.fr/montavont/img-docker/progsys:latest

build_6.1:
  stage: build
  script:
    - cd 06-signaux/01-compteur
    - scons
  artifacts:
    paths:
      - 06-signaux/01-compteur/compteur

# run tests using the binary build before
test_6.1:
  stage: test
  needs: [build_6.1]
  script:
  - |
    echo "starting test"
    cd 06-signaux/01-compteur
    bash tests.sh
