stages:
  - build
  - test

image: registry.app.unistra.fr/montavont/img-docker/progsys:latest

build_2.3:
  stage: build
  script:
    - cd 02-repertoires/03-liste-repertoire
    - scons
  artifacts:
    paths:
      - 02-repertoires/03-liste-repertoire/liste-rep

# run tests using the binary build before
test_2.3:
  stage: test
  needs: [build_2.3]
  script:
  - |
    echo "starting test"
    cd 02-repertoires/03-liste-repertoire
    bash tests.sh
